spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://120.26.198.103:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 120.26.198.103:8848
  application:
    name: gulimall-product
  redis:
    host: 120.26.198.103
    port: 6379
  cache:
    #指定缓存类型为redis
    type: redis
    redis:
    # 指定redis中的过期时间为1h
      time-to-live: 3600000
      cache-null-values: true
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
glmall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10



# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      # 配置逻辑删除 1代表删除 0代表已删除
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 9000




