ipAddr: 120.26.198.103
spring:
  application:
    name: mall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: ${ipAddr}:8848
    sentinel:
      transport:
        dashboard: ${ipAddr}:8333
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: ${ipAddr}
server:
  port: 20000
  # session存活时间
  servlet:
    session:
      timeout: 30m